name: MICA
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.6.2=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-visual-tools=11.6.2=0
  - ffmpeg=4.3=hf484d3e_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - numpy=1.23.4
  - pillow=9.2.0
  - pip=22.2.2
  - python=3.9.15
  - pytorch=1.13.0=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-mutex=1.0=cuda
  - torchaudio=0.13.0=py39_cu116
  - torchvision=0.14.0=py39_cu116
  - pip:
      - albumentations==1.3.0
      - cachetools==5.2.0
      - chumpy==0.70
      - coloredlogs==15.0.1
      - contourpy==1.0.6
      - cycler==0.11.0
      - cython==0.29.32
      - easydict==1.10
      - face-alignment==1.3.5
      - falcon==3.1.1
      - falcon-multipart==0.2.0
      - flatbuffers==22.11.23
      - fonttools==4.38.0
      - google-api-core==2.11.0
      - google-api-python-client==2.69.0
      - google-auth==2.15.0
      - google-auth-httplib2==0.1.0
      - googleapis-common-protos==1.57.0
      - gunicorn==20.1.0
      - gdown
      - httplib2==0.21.0
      - humanfriendly==10.0
      - imageio==2.22.4
      - insightface==0.7
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - llvmlite==0.39.1
      - loguru==0.6.0
      - matplotlib==3.6.2
      - mpmath==1.2.1
      - networkx==2.8.8
      - numba==0.56.4
      - oauth2client==4.1.3
      - onnx==1.13.0
      - onnxruntime==1.13.1
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.6.0.66
      - packaging==21.3
      - prettytable==3.5.0
      - protobuf==3.20.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydrive2==1.15.0
      - pyparsing==3.0.9
      - python-datauri==1.1.0
      - python-dateutil==2.8.2
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qudida==0.0.4
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.1.3
      - scipy==1.9.3
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - tifffile==2022.10.10
      - tqdm==4.64.1
      - trimesh==3.16.4
      - uritemplate==4.1.1
      - wcwidth==0.2.5
      - yacs==0.1.8